### ISSUE TITLE
Stuck on "LORAWAN STARTING"

### ISSUE THREAD

**Issue by alexandredubois** [hkicko/CubeCell-GPS-Helium-Mapper#13]
Hello,
I tried the program setting devEui/appEui/appKey, and in the platform.ini i use the same config as with the jas-williams sketch :
`build_flags = -Wl,-Map,output.map
monitor_speed = 115200
board_build.arduino.lorawan.region = EU868
;board_build.arduino.lorawan.region = US915
board_build.arduino.lorawan.class = CLASS_A
board_build.arduino.lorawan.netmode = OTAA
board_build.arduino.lorawan.adr = ON
board_build.arduino.lorawan.uplinkmode = UNCONFIRMED
board_build.arduino.lorawan.net_reserve = OFF
board_build.arduino.lorawan.rgb = ACTIVE
board_build.arduino.lorawan.debug_level = NONE
; debug_level can be NONE, FREQ, FREQ_AND_DIO
board_build.arduino.lorawan.at_support = OFF
board_build.arduino.lorawan.preamble_length = 8`

But i'm always stuck on the "LORAWAN STARTING" screen at startup. Enabling the DEBUG flag i only see these : 
`AT Rev 1.3
+AutoLPM=1

+LORAWAN=1

+KeepNet=0
+OTAA=1
+Class=A
+ADR=1
+IsTxConfirmed=0
+AppPort=2
+DutyCycle=1000
+ConfirmedNbTrials=4
+ChMask=00000000000000000000FF00
+DevEui=6081F9D53XXXXXXXX(For OTAA Mode)
+AppEui=6081F968AXXXXXXX(For OTAA Mode)
+AppKey=996CC5E5EF5C65D948DECD310BXXXXXX(For OTAA Mode)
+NwkSKey=00000000000000000000000000000000(For ABP Mode)
+AppSKey=00000000000000000000000000000000(For ABP Mode)
+DevAddr=00000000(For ABP Mode)

LoRaWAN EU868 Class A start!

GPS Current baudrate detecting...
GPS Current baudrate detected:19200
GPS baudrate updating to 115200`

The jas-williams sketch works well on my board (except the GPS fix which is veeeerrrry long), and the only difference i noticed on the lorawan part is the userChannelsMask. But replacing it changed nothing :(

Do you have any idea of what i could investigate ? For reference, i'm in Bordeaux, France

**Comment by hkicko** [comment]
Turn ADR off, I don't know why you have it on. 
Your serial debug output suggests it is hanging while it is trying to set the baud rate for communication to the GPS - notice how the last message is GPS baudrate updating to 115200 but there is no follow up message saying GPS baudrate updated to 115200. 
You should make sure you have selected the correct include file for your GPS model - see at the top of main.cpp where it has 2 entries, one for #include "GPS_Air530.h" and one for #include "GPS_Air530Z.h" - you have to comment out the wrong one and uncomment the correct one for your board.

**Comment by hkicko** [comment]
I see the same issue here. Something in the Heltec library is messed up, I guess. It crashes when we try to change the baud rate for talking to the GPS. As a temporary solution - find the line that says GPS.begin(115200); in main.cpp and change it to GPS.begin(); - this fixed it for me.

**Comment by hkicko** [comment]
It was my fault. It should be fixed now.

**Comment by alexandredubois** [comment]
Hi, thank you very much for fixing it so quickly ! I can confirm everything is working now
