### ISSUE TITLE
Version 1.1 uses different SSD1306Wire file

### ISSUE THREAD

**Issue by crashmaxx** [hkicko/CubeCell-GPS-Helium-Mapper#2]
I needed to comment out #include "cubecell_SSD1306Wire.h" and add #include "HT_SSD1306Wire.h" to get it to work with the V1.1 CubeCell HTCC-AB02S

**Comment by hkicko** [comment]
No, version 1.1 of the board does not use different header for the screen, the new version of the platform does. 
You must have missed my commit from Aug 12, 2021 called "Switch to v1.3.1 of "ASR Microelectronics ASR650x" Platform" which does exactly that. 
https://github.com/hkicko/CubeCell-GPS-Helium-Mapper/commit/ec9f1dc9b3476f6d13d7f37664845d12cd6b2577

**Comment by crashmaxx** [comment]
Yes, I was still using a version from before the 12th. Sorry I missed that.
