### ISSUE TITLE
Menu timeout too long

### ISSUE THREAD

**Issue by megabyte2010** [hkicko/CubeCell-GPS-Helium-Mapper#5]
Hi. I reduced the time to menu timeout to 5000ms. I think 30000 too much.

**Comment by hkicko** [comment]
Yes, anybody can change it to whatever duration they feel is good for them.

**Comment by megabyte2010** [comment]
Just to say that your code established a join accepted and some uplinks in a distance of 466km (290 miles) across the Atlantic ocean, with just the cubecell board and a diy ground plane antenna tuned with a nanovna.
________________________________
