### ISSUE TITLE
Personal record

### ISSUE THREAD

**Issue by megabyte2010** [hkicko/CubeCell-GPS-Helium-Mapper#6]
Just to say that your code established a connection some days ago with a  remote gateway and was able to send some uplinks in a distance of 466km (290 miles) across the Atlantic ocean between Madeira island and Canaries islands, with just the cubecell board and a diy ground plane antenna tuned with a nanovna.

**Comment by hkicko** [comment]
I'm not sure I can claim responsibility for that. LoRa is good. The hardware is probably good. I'm just calling an existing function to send. And... there are hotspots that spoof their location, so you never know if that distance is real or not.

**Comment by dagnum** [comment]
Sounds like maybe you were lucky enough to find a worm hole!
