### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by RFingAdam** [hkicko/CubeCell-GPS-Helium-Mapper#7]
Hello, I am requesting information/clarification on the licensing for this project and if it can be used commercially.

I don't see any license called out, so by default it doesn't appear anyone can legally use the code base for any reason..

Thanks!

**Comment by hkicko** [comment]
You can use it. I don't care.

**Comment by aelyacho** [comment]
@hkicko it's still useful to avoid any misconception.
You can easily add one from a template: just go to Insights -> Community Standards -> License -> choose MIT license in your case and commit !

**Comment by hkicko** [comment]
Done.
