### ISSUE TITLE
Not reporting automatically?

### ISSUE THREAD

**Issue by pmcnano** [hkicko/CubeCell-GPS-Helium-Mapper#9]
Idk if I'm just dumb but it's not reporting anything automatically.

I've driven with the device on and it doesn't send or update anything unless I open the menu and select send now. 

Also, I noticed that at some point the screen turns off and I can't turn it on unless I reset the device. 

For instance when it sleeps, I press the button and it wakes up and the screen turns off again and I can't do anything to turn it on. (Wondering if there's something defective with my board)

Thanks!

**Comment by hkicko** [comment]
See if that latest version fixes it. There was an issue with the latest version of the Heltec platform libraries that I hope are fixed now. The older versions were allowing me to do some things that the new version does not allow, so I had to implement a workaround.

**Comment by pmcnano** [comment]
Hey @hkicko thanks! Sorry for the delay I couldn't test it until today!

It works perfectly! Thanks!
